### ISSUE TITLE
Ambiguous pin assignment comments in examples

### ISSUE THREAD

**Issue by serlecu** [luni64/EncoderTool#37]
Hi,

I found really confusing these comments in the multiplexed examples.
Is there any reason why QH_A is related to the QH  pin of the B register and not the A?

[ Multiplex 74HC165 tutorial ](https://github.com/luni64/EncoderTool/blob/master/examples/2_multiplexing/multiplexed_74165/multiplexed_74165.ino)
```
constexpr unsigned QH_A = 0;   // output pin QH of shift register B
constexpr unsigned QH_B = 1;   // output pin QH of shift register A
```

[ Multiplex Callbacks tutorial ](https://github.com/luni64/EncoderTool/blob/master/examples/3_callbacks/mplexCallbacks/mplexCallbacks.ino)
```
constexpr unsigned QH_A = 2;   // output pin QH of shift register B
constexpr unsigned QH_B = 3;   // output pin QH of shift register A
```

**Comment by luni64** [comment]
>Is there any reason why QH_A is related to the QH pin of the B register and not the A?

Actually no, this seems to be a typo. I'll fix it. Thanks for spotting this.
