### ISSUE TITLE
Any way to output debug info?

### ISSUE THREAD

**Issue by djex** [luni64/EncoderTool#7]
I've been trying to get EncorderTool to work for hours now. I'm trying to use it with two SN74HC165N shift registers and a few Burns PEC16 mechanical quadrature encoders (no detent). I'm using a Teensy 3.2. I've tried every possible wiring combination and code but nothing seems to work. I made sure to follow the multiplexed 74165 example as well. I guess next step is to validate if the shift registers are even working. Is there any debug info I can get from EncoderTool? Maybe like raw data or something so I can see if it's reading anything from the shift registers?

**Comment by ElectroTechnique** [comment]
> Great, someone else stumbled over this some time ago. Completely forgot it. Might be a good idea to mention this somewhere in the documentation...

Please do so IMMEDIATELY! I have four encoders attached to A-D on the shift register and couldn't get any output. Thanks for all the work on this.

**Comment by luni64** [comment]
Done
